// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAYCXx5c5alvDuDBNK7sKk7DBqjOYWaNuc',
    appId: '1:557160444131:web:19c33b1a93de1e051115d6',
    messagingSenderId: '557160444131',
    projectId: 'signing-example-7a53a',
    authDomain: 'signing-example-7a53a.firebaseapp.com',
    storageBucket: 'signing-example-7a53a.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBKdDC9zPYRekF2RYQY_kfXizFXaSI0neY',
    appId: '1:557160444131:android:d7f6ac786d725df81115d6',
    messagingSenderId: '557160444131',
    projectId: 'signing-example-7a53a',
    storageBucket: 'signing-example-7a53a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDYGn06bwDs9O5_OMWcOOmaxPT_ni52Y6s',
    appId: '1:557160444131:ios:4ef0d75bfb23532a1115d6',
    messagingSenderId: '557160444131',
    projectId: 'signing-example-7a53a',
    storageBucket: 'signing-example-7a53a.appspot.com',
    iosClientId: '557160444131-m1alaa1njk1886qdrbnn46or0i7ai7di.apps.googleusercontent.com',
    iosBundleId: 'com.example.finalapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDYGn06bwDs9O5_OMWcOOmaxPT_ni52Y6s',
    appId: '1:557160444131:ios:d7064cd0d740b8861115d6',
    messagingSenderId: '557160444131',
    projectId: 'signing-example-7a53a',
    storageBucket: 'signing-example-7a53a.appspot.com',
    iosClientId: '557160444131-c9bjpu74j3hjlgtltcctef4s09atfgoe.apps.googleusercontent.com',
    iosBundleId: 'com.example.finalapp.RunnerTests',
  );
}
